%% Run experiment to all TCD data
% To display the mean of results per label
% rTable = varfun(@mean, results, 'InputVariables', @isnumeric, 'GroupingVariables', 'label')
% writetable(rTable, '
dataList = { ...
    struct('subj', 's1', 'act', 'Acting1'), ...
    struct('subj', 's1', 'act', 'Acting2'), ...
    struct('subj', 's1', 'act', 'Acting3'), ...
    struct('subj', 's1', 'act', 'freestyle1'), ...
    struct('subj', 's1', 'act', 'freestyle2'), ...
    struct('subj', 's1', 'act', 'freestyle3'), ...
    struct('subj', 's1', 'act', 'rom1'), ...
    struct('subj', 's1', 'act', 'rom2'), ...
    struct('subj', 's1', 'act', 'rom3'), ...
    struct('subj', 's1', 'act', 'walking1'), ...
    struct('subj', 's1', 'act', 'walking2'), ...
    struct('subj', 's1', 'act', 'walking3'), ...
    struct('subj', 's2', 'act', 'acting1'), ...
    struct('subj', 's2', 'act', 'acting2'), ...
    struct('subj', 's2', 'act', 'acting3'), ...
    struct('subj', 's2', 'act', 'freestyle1'), ...
    struct('subj', 's2', 'act', 'freestyle2'), ...
    struct('subj', 's2', 'act', 'freestyle3'), ...
    struct('subj', 's2', 'act', 'rom1'), ...
    struct('subj', 's2', 'act', 'rom2'), ...
    struct('subj', 's2', 'act', 'rom3'), ...
    struct('subj', 's2', 'act', 'walking1'), ...
    struct('subj', 's2', 'act', 'walking2'), ...
    struct('subj', 's2', 'act', 'walking3'), ...
    struct('subj', 's3', 'act', 'acting1'), ...
    struct('subj', 's3', 'act', 'acting2'), ...
    struct('subj', 's3', 'act', 'acting3'), ...
    struct('subj', 's3', 'act', 'freestyle1'), ...
    struct('subj', 's3', 'act', 'freestyle2'), ...
    struct('subj', 's3', 'act', 'freestyle3'), ...
    struct('subj', 's3', 'act', 'rom1'), ...
    struct('subj', 's3', 'act', 'rom2'), ...
    struct('subj', 's3', 'act', 'rom3'), ...
    struct('subj', 's3', 'act', 'walking1'), ...
    struct('subj', 's3', 'act', 'walking2'), ...
    struct('subj', 's3', 'act', 'walking3'), ...
    struct('subj', 's4', 'act', 'acting3'), ...
    struct('subj', 's4', 'act', 'freestyle1'), ...
    struct('subj', 's4', 'act', 'freestyle3'), ...
    struct('subj', 's4', 'act', 'rom3'), ...
    struct('subj', 's4', 'act', 'walking2'), ...
    struct('subj', 's5', 'act', 'acting3'), ...
    struct('subj', 's5', 'act', 'freestyle1'), ...
    struct('subj', 's5', 'act', 'freestyle3'), ...
    struct('subj', 's5', 'act', 'rom3'), ...
    struct('subj', 's5', 'act', 'walking2'), ...
};
dataList = {
    struct('subj', 's5', 'act', 'walking2'), ...
};
dir = 'totalcapture';
expDir = "./experiments";

% setups = { ... % base scenarios 
%     struct('accData', 'v', 'oriData', 'v'), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 0, 'hjc', 0), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 0), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 0, 'hjc', 1), ...
%     ... % different data sets
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 1), ...
%     struct('accData', 'v', 'oriData', 'x', 'zupt', 1, 'hjc', 1), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 1), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 1), ...
%     struct('accData', 'xf', 'oriData', 'v', 'zupt', 1, 'hjc', 1), ...
%     struct('accData', 'xf', 'oriData', 'x', 'zupt', 1, 'hjc', 1), ...
%     ... % different hjc
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 2), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 2), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 3), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 3), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 4), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 4), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 9), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 9), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 11), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 11), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 11), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 12), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 12), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 12), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 13), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 13), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 13), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 14), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 14), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 14), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 15), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 15), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 15), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 16), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 16), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 16), ...
%     ... % different acc_bias
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 1, ...
%            'accbias', 1, 'P', eye(27, 27)*100), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 1, ...
%            'accbias', 1, 'P', eye(27, 27)*100), ...      
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 1, ...
%            'accbias', 2, 'P', eye(27, 27)*100), ... 
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 1, ...
%            'accbias', 2, 'P', eye(27, 27)*100), ...
%     ... % hjc v2 (no knee lock)
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 0, 'hjc', 101), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 101), ...
%     struct('accData', 'v', 'oriData', 'x', 'zupt', 1, 'hjc', 101), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 101), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 101), ...
%     struct('accData', 'xf', 'oriData', 'v', 'zupt', 1, 'hjc', 101), ...
%     struct('accData', 'xf', 'oriData', 'x', 'zupt', 1, 'hjc', 101), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 102), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 102), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 103), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 103), ...
%     ... % hjc v2 (no knee lock) + smoothly constrained kf
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 121), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 121), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 121), ...
%     ... % hjc v2 + fmincon
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 141), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 141), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 141), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 142), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 142), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 142), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 143), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 143), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 143), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 144), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 144), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 144), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 145), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 145), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 145), ...
%     struct('accData', 'v', 'oriData', 'v', 'zupt', 1, 'hjc', 146), ...
%     struct('accData', 'x', 'oriData', 'v', 'zupt', 1, 'hjc', 146), ...
%     struct('accData', 'x', 'oriData', 'x', 'zupt', 1, 'hjc', 146), ...
%     ... % EKVv3
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 1), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 1), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 1), ...
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 102), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 102), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 102), ...
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 105), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 105), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 105), ...
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 101), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 101), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 101), ...
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 104), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 104), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 104), ...
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 103), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 103), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 103), ...
%     struct('accData', 'v', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 106), ...
%     struct('accData', 'x', 'oriData', 'v', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 106), ...
%     struct('accData', 'x', 'oriData', 'x', 'est', 'ekfv3', ...
%            'zupt', 1, 'cstr', 106), ...
%     };
    
setups = {
    struct('label', 'Dxxx+ZUPT+C001', 'est', 'ekfv3', ...
           'accData', 'x', 'oriData', 'x', 'zuptData', 'x', ...
           'zupt', 1, 'cstr', 1, 'P', 0.5), ...
    struct('label', 'Dxvv+ZUPT+C001', 'est', 'ekfv3', ...
           'accData', 'x', 'oriData', 'v', 'zuptData', 'x', ...
           'zupt', 1, 'cstr', 1, 'P', 0.5), ...
    struct('label', 'Dxxx+ZUPT+C002', 'est', 'ekfv3', ...
           'accData', 'x', 'oriData', 'x', 'zuptData', 'x', ...
           'zupt', 1, 'cstr', 2, 'P', 0.5), ...
    struct('label', 'Dxvv+ZUPT+C002', 'est', 'ekfv3', ...
           'accData', 'x', 'oriData', 'v', 'zuptData', 'x', ...
           'zupt', 1, 'cstr', 2, 'P', 0.5), ...
};           

%     struct('label', 'Dxxx+ZUPT+C104', 'est', 'ekfv3', ...
%            'accData', 'x', 'oriData', 'x', 'zuptData', 'x', ...
%            'zupt', 1, 'cstr', 104), ...
%     struct('label', 'Dxvv+ZUPT+C104', 'est', 'ekfv3', ...
%            'accData', 'x', 'oriData', 'v', 'zuptData', 'x', ...
%            'zupt', 1, 'cstr', 104), ...
%     struct('label', 'Dxxx+ZUPT+C105', 'est', 'ekfv3', ...
%            'accData', 'x', 'oriData', 'x', 'zuptData', 'x', ...
%            'zupt', 1, 'cstr', 105), ...
%     struct('label', 'Dxvv+ZUPT+C105', 'est', 'ekfv3', ...
%            'accData', 'x', 'oriData', 'v', 'zuptData', 'x', ...
%            'zupt', 1, 'cstr', 105), ...
           
dataN = length(dataList);
dataInstances = {};
results = table();

for i = 1:dataN
% for i = 1:3
    n = dataList{i};
    name = sprintf('%s-%s-%s', 'tcd', n.subj, lower(n.act));
    dataPath = sprintf('%s/mat/%s.mat', dir, name);
    if exist(dataPath, 'file')
        load(dataPath, 'data');
    else
        data = struct('name', name, ...
            'fnameV', sprintf('%s/vicon/%s/%s_BlenderZXY_YmZ.bvh', dir, n.subj, lower(n.act)), ...
            'fnameS', sprintf('%s/gyroMag/%s/%s_Xsens_AuxFields.sensors', dir, n.subj, n.act), ...
            'fnameCIB', sprintf('%s/imu/%s/%s_%s_calib_imu_bone.txt', dir, n.subj, n.subj, lower(n.act)), ...
            'fnameCIR', sprintf('%s/imu/%s/%s_%s_calib_imu_ref.txt', dir, n.subj, n.subj, lower(n.act)) ...
            );
        data.dataV = tcdlib.BVHBody.loadBVHFile(data.fnameV, 'mm');
        data.dataV = tcdlib.BVHBody.loadBVHFile(data.fnameV, 'mm');
        data.dataS = tcdlib.XsensBody.loadSensorFile(data.fnameS);
        data.calibIB = tcdlib.XsensBody.loadCalib(data.fnameCIB);
        data.calibIR = tcdlib.XsensBody.loadCalib(data.fnameCIR);
        save(dataPath, 'data');
    end
    display(sprintf("Data %3d/%3d: %s", i, dataN, data.name));
    r = tcdExperiment01(data.dataV, data.dataS, data.calibIB, data.calibIR, ...
                        data.name, setups, expDir);
    results = [results; struct2table(r)];
%     dataInstances{i} = tmp;
end