% ======================================================================
%> @brief Plot the lower body
%> @author Luke Sy
%>
%> Plot the lower body
%> 
%> @param body Body instance to be plotted
%> @param t time point to be plotted
%> @param showGround show ground
%> @retval p plot object
% ======================================================================
function p = plotLowerBody(body, t, showGround)    
    if nargin <= 2
        showGround = false;
    end
    
    pelvL = line([body.LFEP(t,1) body.MIDPEL(t,1) body.RFEP(t,1)], ...
                 [body.LFEP(t,2) body.MIDPEL(t,2) body.RFEP(t,2)], ...
                 [body.LFEP(t,3) body.MIDPEL(t,3) body.RFEP(t,3)], ...
                 'Color', char(body.xyzColor(2)), 'LineWidth', 2);
    pelvL.Marker = body.ptSymbol;
    lfemL = line([body.LFEP(t,1) body.LFEO(t,1)], ...
                 [body.LFEP(t,2) body.LFEO(t,2)], ...
                 [body.LFEP(t,3) body.LFEO(t,3)], ...
                 'Color', char(body.xyzColor(3)), 'LineWidth', 2, ...
                 'LineStyle', '--');
    rfemL = line([body.RFEP(t,1) body.RFEO(t,1)], ...
                 [body.RFEP(t,2) body.RFEO(t,2)], ...
                 [body.RFEP(t,3) body.RFEO(t,3)], ...
                 'Color', char(body.xyzColor(1)), 'LineWidth', 2, ...
                 'LineStyle', '--');
    ltibL = line([body.LFEO(t,1) body.LTIO(t,1)], ...
                 [body.LFEO(t,2) body.LTIO(t,2)], ...
                 [body.LFEO(t,3) body.LTIO(t,3)], ...
                 'Color', char(body.xyzColor(3)), 'LineWidth', 2);
    ltibL.Marker = body.ptSymbol;
    rtibL = line([body.RFEO(t,1) body.RTIO(t,1)], ...
                 [body.RFEO(t,2) body.RTIO(t,2)], ...
                 [body.RFEO(t,3) body.RTIO(t,3)],...
                 'Color', char(body.xyzColor(1)), 'LineWidth', 2);
    rtibL.Marker = body.ptSymbol;
    if showGround
        [ptsX, ptsY, ptsZ] = body.groundCoordinates();
        patch(ptsX, ptsY, ptsZ, 'k', 'FaceAlpha', .5, 'LineStyle', ':')
    end
end